name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-rc.*'

jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@uniwise'

      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

      - name: Build package
        run: yarn build

      - name: Set package version
        run: yarn version --new-version "${GITHUB_REF:11}" --no-git-tag-version

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}